### PR TITLE
Adding more properties to get and update methods and fixing failing i…

### LINKED ISSUE #2465: Missing response properties on the branch protection api
There are several newer properties on the branch protection api that are missing 

- required_signatures
- required_linear_history
- allow_force_pushes
- allow_deletions
- required_conversation_resolution

Relevant response model https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Response/BranchProtection.cs

Api
https://docs.github.com/en/rest/branches/branch-protection#get-branch-protection

### PR DESCRIPTION
**Pull request by JonruAlveus**
Fixes #2465 

Adding more properties to get and update methods and fixing failing integration tests

### CODE REVIEW

File: Octokit/Models/Response/BranchProtection.cs [hunk 1]
```diff
@@ -9,41 +9,85 @@ namespace Octokit
...
+            RequiredSignatures = requiredSignatures;
         }
 
+
+
         /// <summary>
         /// Status check settings for the protected branch
         /// </summary>
-        public BranchProtectionRequiredStatusChecks RequiredStatusChecks { get; protected set; }
+        public BranchProtectionRequiredStatusChecks RequiredStatusChecks { get; private set; }
```
Comment (nickfloyd) [inline Octokit/Models/Response/BranchProtection.cs:45]: 👍 Thanks for the clean-up here! 🎉

**Review by nickfloyd — APPROVED** [review]
LGTM!  Thanks for getting the knocked out!
