### PR TITLE
fix language with spaces giving wrong results [#1607]

### LINKED ISSUE #1607: Search API: languages with space(s) fetch wrong results
The following code:

```csharp
var client = new GitHubClient();
var searchRepositoriesRequest = new SearchRepositoriesRequest { Language = Language.GettextCatalog };

var result = await client.Search.SearchRepo(searchRepositoriesRequest);
```

hits the following URL: https://api.github.com/search/repositories?q=language:Gettext%20Catalog, which returns incorrect results - see the first repo has `language: "JavaScript"`.

When surrounding the language with double quotes, like https://api.github.com/search/repositories?q=language:"Gettext%20Catalog", then the fetched results are correct as all the repos have `language: "Gettext Catalog"`.

Fix should be easy as we could use double quotes around the `language` value no matter if it contains spaces or not.

### PR DESCRIPTION
**Pull request by Dagizmo**
Fixes #1607

### CODE REVIEW

**Comment by shiftkey** [comment]
@Dagizmo I think the only thing that's missing from this PR is a test that verifies we send through the space in the correct way. Would you be able to add that in?

**Comment by Dagizmo** [comment]
ok, will look into that.

File: Octokit/Models/Request/SearchUsersRequest.cs [hunk 1]
```diff
@@ -117,7 +117,7 @@ public override IReadOnlyList<string> MergedQualifiers()
 
             if (Language != null)
             {
-                parameters.Add(string.Format(CultureInfo.InvariantCulture, "language:\"{0}\"", Language));
+                parameters.Add(string.Format(CultureInfo.InvariantCulture, "language:\"{0}\"", Language.ToParameter()));
```
Comment (Dagizmo) [inline Octokit/Models/Request/SearchUsersRequest.cs]: Actually found that this part didn't use to Parameter so named languages such as CPlusPlus was parsed as "CPlusPlus" instead of "cpp"

**Comment by Dagizmo** [comment]
updated :D

**Comment by shiftkey** [comment]
release_notes: address encoding of spaces when using Search API
