### PR TITLE
bugfix: improve fallback when StringEnum encounters null value

### LINKED ISSUE #2052: NullReferenceException when Repository.GetAllTeams() contains nested teams
Octokit.NET v0.36.0

```cs
client.Repository.GetAllTeams("AnyTestOrg", "how-to-use-grid-with-vertical-scrollbar-in-full-screen-mode-100-width-and-height-e1081").Wait();
```

throws an exception:
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at GitHubApiTest.Program.Main(String[] args) in F:\Projects\GitHubApiTest\GitHubApiTest\Program.cs:line 62

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

Inner exception stack trace:
```
   at Octokit.Reflection.ReflectionUtils.<>c__DisplayClass41_0.<GetSetMethodByExpression>b__0(Object source, Object val) in C:\Users\shiftkey\src\octokit.net\Octokit\SimpleJson.cs:line 2075
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\src\octokit.net\Octokit\SimpleJson.cs:line 1495
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\src\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 193
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\src\octokit.net\Octokit\SimpleJson.cs:line 1495
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\src\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 193
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\src\octokit.net\Octokit\SimpleJson.cs:line 1522
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\src\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 193
   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in C:\Users\shiftkey\src\octokit.net\Octokit\SimpleJson.cs:line 591
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in C:\Users\shiftkey\src\octokit.net\Octokit\SimpleJson.cs:line 603
   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json) in C:\Users\shiftkey\src\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 22
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in C:\Users\shiftkey\src\octokit.net\Octokit\Http\JsonHttpPipeline.cs:line 66
   at Octokit.Connection.<Run>d__57`1.MoveNext() in C:\Users\shiftkey\src\octokit.net\Octokit\Http\Connection.cs:line 628
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<GetPage>d__42`1.MoveNext() in C:\Users\shiftkey\src\octokit.net\Octokit\Http\ApiConnection.cs:line 620
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext() in C:\Users\shiftkey\src\octokit.net\Octokit\Http\ApiConnection.cs:line 197
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext() in C:\Users\shiftkey\src\octokit.net\Octokit\Clients\ApiPagination.cs:line 37
```

FIddler output:

image

If I move ASPxGridView to the root, the error is gone:

image

### PR DESCRIPTION
**Pull request by shiftkey**
Resolves #2052

## Testing

To aid with testing this PR, you can add a `NuGet.config` file to the root of your project that adds our beta packages feed:

```
<configuration>
    <packageSources>
        <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
        <add key="Octokit beta" value=" https://ci.appveyor.com/nuget/octokit-net" />
    </packageSources>
</configuration>
```

Then, switch your version to the beta release just published, currently `0.45.0-fix-teams-deseri0005`, and try to verify the fix. I'm still working to try and reproduce this on my side, but I have an idea of where it's lurking...

### CODE REVIEW

**Comment by shiftkey** [comment]
@cliffchapmanrbx @MikhailTymchukDX are either of you able to verify this PR fixes the problem for you? I'd love to be able to confirm this is good before publishing an update to everyone...

File: Octokit/Http/SimpleJsonSerializer.cs [hunk 1]
```diff
@@ -190,6 +190,18 @@ public override object DeserializeObject(object value, Type type)
...
+                if (ReflectionUtils.IsStringEnumWrapper(type))
+                {
+                    // this check is a workaround for https://github.com/octokit/octokit.net/issues/2052
+                    // as the API is returning a null value where the enum is
+                    // expecting something like a string
+                    //
+                    // this should be removed once we can confirm the GitHub API
+                    // is no longer returning a null for the parent Team's
+                    // permission value
+                    return Activator.CreateInstance(type, "null");
```
Comment (cliffchapmanrbx) [inline Octokit/Http/SimpleJsonSerializer.cs]: I used `null` in my code s well as for the ParameterAttribute for the enum. `PermissionLevel` appears to use the word `none` as its value though. Do you need to change this to be `none` instead of `null`?

**Comment by cliffchapmanrbx** [comment]
@shiftkey You'd also need access to our GitHub Enterprise server which might be difficult :)

I added a comment about none vs null, I'm a bit slammed with meetings today (under Bay Area shelter in place order) so I'll try and check this as soon as I can.

File: Octokit/Http/SimpleJsonSerializer.cs (hunk 1 above)
Comment (shiftkey) [reply Octokit/Http/SimpleJsonSerializer.cs]: I prefer `null` here to explicitly indicate no value was found, and I want this to be different to the `none` scenario that might be valid here. 

In the test itself you'll see that I can't parse out a valid value from this enum.

```C#
Assert.Equal("null", result.Parent.Permission.StringValue);

PermissionLevel value;
Assert.False(result.Parent.Permission.TryParse(out value));
```

This fixes the deserialization issue, and leverages our existing string-like enums to handle unknown values rather than mapping this `null` to `none`.

**Comment by shiftkey** [comment]
@cliffchapmanrbx aha yes, that's also helpful context because you might be working against an older version of the GitHub API depending on your version of GHE

File: Octokit/Http/SimpleJsonSerializer.cs (hunk 1 above)
Comment (cliffchapmanrbx) [reply Octokit/Http/SimpleJsonSerializer.cs]: Ahha, that makes more sense, thanks!

**Comment by cliffchapmanrbx** [comment]
We keep it up to date specifically to avoid those kinds of problems.

Fortunately (?) my next meeting just got cancelled so I've got an hour to play around with this.

**Comment by shiftkey** [comment]
@cliffchapmanrbx do you know which version of GHE you are working against? This will help me to confirm where it was introduced and whether it's been fixed since.

**Comment by cliffchapmanrbx** [comment]
2.20.2 as of the middle of last week, previously we were on 2.19.5. I don't know if the upgrade caused this issue, or someone shuffling some teams around and suddenly making them nested was what surfaced it. The original bug report is from December.

**Comment by cliffchapmanrbx** [comment]
I can confirm that we no longer see the error from repos with nested teams. I appreciate the hustle!

**Comment by shiftkey** [comment]
Thanks for confirming @cliffchapmanrbx. 

> The original bug report is from December.

Yeah, I suspect that one was also from GitHub Enterprise but I forgot to ask at the time.

> Do you have an ETA on when this might be available as a new version? 

Aiming for tonight once I've cleared out some other work.

**Comment by shiftkey** [comment]
release_notes: Fix for deserializing issue when parent team has `null` set for `Permission` in some GitHub Enterprise environments.

**Comment by shiftkey** [comment]
@cliffchapmanrbx the fix has been released https://github.com/octokit/octokit.net/releases/tag/v0.45.0 and is being indexed on NuGet as we speak...

**Comment by cliffchapmanrbx** [comment]
I just updated my local copy to 0.45.0 and can confirm it is still good. Rolling it out to our internal services now. I really appreciate the quick turnaround on this once we had it isolated 👍

File: Octokit/Models/Response/Team.cs [hunk 2]
```diff
@@ -67,7 +67,7 @@ public Team(string url, int id, string nodeId, string slug, string name, string
         /// <summary>
         /// permission attached to this team
         /// </summary>
-        public StringEnum<Permission> Permission { get; protected set; }
+        public StringEnum<PermissionLevel> Permission { get; protected set; }
```
Comment (StingyJack) [inline Octokit/Models/Response/Team.cs:70]: this makes `Value 'pull' is not a valid 'PermissionLevel' enum value` get thrown when trying to serialize a repo object with codeowners that includes a GH team
