### PR TITLE
Fix Issue Timeline exceptions by adding new EventInfoState values

### LINKED ISSUE #1525: Timeline API: Exception: {"Requested value 'reviewed' was not found."}
Note: gitHubClient.PullRequest.Get works fine for the same pull request
StackTrace:
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\code\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 125
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\code\octokit.net\Octokit\SimpleJson.cs:line 1478
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\code\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 166
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\code\octokit.net\Octokit\SimpleJson.cs:line 1505
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in C:\Users\shiftkey\code\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 166
   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in C:\Users\shiftkey\code\octokit.net\Octokit\SimpleJson.cs:line 583
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in C:\Users\shiftkey\code\octokit.net\Octokit\SimpleJson.cs:line 595
   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json) in C:\Users\shiftkey\code\octokit.net\Octokit\Http\SimpleJsonSerializer.cs:line 21
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in C:\Users\shiftkey\code\octokit.net\Octokit\Http\JsonHttpPipeline.cs:line 62
   at Octokit.Connection.<Run>d__53`1.MoveNext() in C:\Users\shiftkey\code\octokit.net\Octokit\Http\Connection.cs:line 560
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<GetPage>d__40`1.MoveNext() in C:\Users\shiftkey\code\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext() in C:\Users\shiftkey\code\octokit.net\Octokit\Http\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext() in C:\Users\shiftkey\code\octokit.net\Octokit\Clients\ApiPagination.cs:line 0

### LINKED ISSUE #1559: Exception thrown: Requested value 'linecommented' was not found.
Here is the short repro case, using the Octokit.net v0.24.0 nuget package:
```
// https://github.com/Microsoft/WinObjC/pull/2106
var ghClient = new GitHubClient(new Octokit.ProductHeaderValue("crash-repro"));
var issueEvents = ghClient.Issue.Timeline.GetAllForIssue(37950166, 2106).Result;
```

Stack:
```
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\\repos\\octokit.net\\Octokit\\Http\\SimpleJsonSerializer.cs:line 124
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in D:\\repos\\octokit.net\\Octokit\\SimpleJson.cs:line 1478
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\\repos\\octokit.net\\Octokit\\Http\\SimpleJsonSerializer.cs:line 165
   at Octokit.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in D:\\repos\\octokit.net\\Octokit\\SimpleJson.cs:line 1505
   at Octokit.Internal.SimpleJsonSerializer.GitHubSerializerStrategy.DeserializeObject(Object value, Type type) in D:\\repos\\octokit.net\\Octokit\\Http\\SimpleJsonSerializer.cs:line 165
   at Octokit.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in D:\\repos\\octokit.net\\Octokit\\SimpleJson.cs:line 583
   at Octokit.SimpleJson.DeserializeObject[T](String json, IJsonSerializerStrategy jsonSerializerStrategy) in D:\\repos\\octokit.net\\Octokit\\SimpleJson.cs:line 595
   at Octokit.Internal.SimpleJsonSerializer.Deserialize[T](String json) in D:\\repos\\octokit.net\\Octokit\\Http\\SimpleJsonSerializer.cs:line 21
   at Octokit.Internal.JsonHttpPipeline.DeserializeResponse[T](IResponse response) in D:\\repos\\octokit.net\\Octokit\\Http\\JsonHttpPipeline.cs:line 62
   at Octokit.Connection.<Run>d__54`1.MoveNext() in D:\\repos\\octokit.net\\Octokit\\Http\\Connection.cs:line 574
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<GetPage>d__41`1.MoveNext() in D:\\repos\\octokit.net\\Octokit\\Http\\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiConnection.<>c__DisplayClass17_0`1.<<GetAll>b__0>d.MoveNext() in D:\\repos\\octokit.net\\Octokit\\Http\\ApiConnection.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octokit.ApiPagination.<GetAllPages>d__0`1.MoveNext() in D:\\repos\\octokit.net\\Octokit\\Clients\\ApiPagination.cs:line 0"	string
```

### PR DESCRIPTION
**Pull request by ryangribble**
Fixes #1559 
Fixes #1525

This fix adds 3 more undocumented event types in the TimeLine API: `linecommented` `commitcommented` and `reviewed`

Also added an integration test that will hopefully help with identifying more missing values in the future, it now runs against the most recent 20 closed PRs and 20 open issues in a heavy activity repository.  

I picked [Microsoft/vscode](https://github.com/Microsoft/vscode) 😀 the theory being that it's a very active repository, and the most recent activity is more likely to have new event types in their timeline/event stream.

The strategy seemed to work, as I discovered 2 extra event types that hadn't been reported by users as causing a crash yet 😸 

In the short term, we will still throw an exception whenever we encounter an event type not previously implemented, a potential longer term solution is being hashed out in #1504

### CODE REVIEW

**Comment by ryangribble** [comment]
If someone can have a 👀 over this before I merge it, that would be great!  😀

File: Octokit/Models/Response/EventInfo.cs [hunk 1]
```diff
@@ -204,6 +204,23 @@ public enum EventInfoState
...
+        /// <summary>
+        /// The issue was reveiewed.
+        /// </summary>
+        Reviewed,
+
+        /// <summary>
+        /// A line comment was made.
+        /// </summary>
+        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Linecommented")]
+        Linecommented,
```
Comment (shiftkey) [inline Octokit/Models/Response/EventInfo.cs]: Could these be cased as `LineCommented` and `CommitCommented`? Or is this a deserialization issue?

File: Octokit.Tests.Integration/Clients/IssueTimelineClientTests.cs [hunk 2]
```diff
@@ -54,12 +45,48 @@ public IssueTimelineClientTests()
...
+
+            // 20 most recent open Issues
+            search.Type = IssueTypeQualifier.Issue;
+            search.State = ItemState.Open;
+            var issueResults = await github.Search.SearchIssues(search);
+            foreach (var issue in issueResults.Items)
+            {
+                var timelineEventInfos = await _issueTimelineClient.GetAllForIssue("microsoft", "vscode", issue.Number);
+
+                Assert.NotNull(timelineEventInfos);
```
Comment (shiftkey) [inline Octokit.Tests.Integration/Clients/IssueTimelineClientTests.cs]: `Assert.NotEmpty` here too?

**Comment by shiftkey** [comment]
@ryangribble left a couple of minor comments, everything else is :gem:

File: Octokit/Models/Response/EventInfo.cs (hunk 1 above)
Comment (ryangribble) [inline Octokit/Models/Response/EventInfo.cs]: The API value is all lowercase, pretty sure if we do camel case on our side we'll be looking for an underscore in the API value

**Comment by eriawan** [comment]
@ryangribble just a suggestion, I think it's easier to suppress CA warnings as project scope instead of class/method/property scope for CA rule of 1704. 🙂 
This rule is mostly pedantic in a sense it will limit the expressiveness of naming class/method/property, and it's easier and faster (in compile time) to just suppress it on project scope, not at different source on class/method/property.

**Comment by shiftkey** [comment]
> This rule is mostly pedantic in a sense it will limit the expressiveness of naming class/method/property, and it's easier and faster (in compile time) to just suppress it on project scope, not at different source on class/method/property.

I disagree. The explicitness of this rule means violations (whether necessary or otherwise) are easier to identify. Doing things at a project level makes it easier to ignore these sorts of issues.

File: Octokit/Models/Response/EventInfo.cs (hunk 1 above)
Comment (shiftkey) [inline Octokit/Models/Response/EventInfo.cs]: @ryangribble I thought we could do something like [this]9https://github.com/octokit/octokit.net/blob/c9b2c1260bc87b7782d4fd9645d43a8885203923/Octokit/Models/Response/Reaction.cs#L10) here?

```csharp
[Parameter(Value = "linecommented")]
LineCommented,
[Parameter(Value = "commitcommented")]
CommitCommented
```

Comment (ryangribble) [inline Octokit/Models/Response/EventInfo.cs]: Yeah so on looking into this more I realised we dont even need to tag with the `Parameter()` since these are only response enums and our deserializer removes underscores and does a case insensitive `Enum.Parse()` anyway :+1:

**Comment by shiftkey** [comment]
@ryangribble ugh, CI failures on macOS

> The command "curl -o "/tmp/mdk.pkg" -fL http://download.mono-project.com/archive/4.2.3/macos-10-x86/MonoFramework-MDK-4.2.3.macos10.xamarin.x86.pkg" failed and exited with 56 during .

**Comment by ryangribble** [comment]
kicked the builds and they are ✅ now

**Comment by ryangribble** [comment]
@shiftkey not sure if you wanted to close out reviewing this or not.  Ill merge it in a day or two if I haven't heard back

**Comment by shiftkey** [comment]
@ryangribble :shipit:

**Comment by ryangribble** [comment]
release_notes: Fix `IssueTimelineClient` deserialization exceptions by adding new `EventInfoState` values
