### PR TITLE
fix: Allow `zip` MIME type

### LINKED ISSUE #2898: [BUG]: Download Artifact - Content Stores Differing Content-Types Cause Errors
### What happened?

Afternoon!

When calling `ActionsArtifactClient.DownloadArtifact`, the download is often, or always, redirected to another server that holds the actual artifact.

In my experience, if the artifact happens to sit on _https://pipelinesghubeus10.actions.githubusercontent.com_, then the `Content-Type` returned is `application/zip` and all is well, but if the artifact happens to reside on _https://productionresultssa10.blob.core.windows.net_, then the `Content-Type` is `zip` and it all starts to go wrong.

There's a check in `HttpClientAdapter.BuildResponse` for the content type, which fails, then the response is read as a string, not a stream, and `Connection.GetRawStream` attempts to cast the string as a stream, understandably gets null, and returns null to the caller.

Easy to fix badly; perhaps harder to fix well.

### Versions

Octokit 10.0.0

### Relevant log output

_No response_

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by thomhurst**
Fixes #2898

### CODE REVIEW

File: Octokit/Http/HttpClientAdapter.cs [hunk 1]
```diff
@@ -81,6 +81,7 @@ protected virtual async Task<IResponse> BuildResponse(HttpResponseMessage respon
                 AcceptHeaders.RawContentMediaType,
                 "application/zip" ,
                 "application/x-gzip" ,
+                "zip" , // Not a standard MIME type but see issue #2898
```
Comment (nickfloyd) [inline Octokit/Http/HttpClientAdapter.cs:84]: While I am not super excited about not using the proper representation (asper the mdm web docs and iana) - I get the situation here.  Thank you for making sure this is commented with context. ❤️

**Review by nickfloyd — APPROVED** [review]
Thanks again for this change @thomhurst
